name: Build/Publish Develop Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all commits/branches
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mike mkdocs-macros-plugin
      - run: mike deploy --push --update-aliases dev
      - run: |
          # prevent step from failing on nonzero exit code
          set +e
          # set default version for mike to point to
          # default to the latest version if it exists
          # if no latest, then default to the dev version
          git ls-tree gh-pages | grep -q "latest" -
          if [ "${?}" -eq 1 ]
          then
            default_mike_version="dev"
          else
            default_mike_version="latest"
          fi
          mike set-default --push "${default_mike_version}"
